// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cifvxgioremibcacoyeg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpZnZ4Z2lvcmVtaWJjYWNveWVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMzczMjQsImV4cCI6MjA2MDgxMzMyNH0.FJDRsXmNXys26nQVyBVYJ0M7-LzK8utuBnf7oVtMrEI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);